// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjopnfhzsufmdybtxipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqb3BuZmh6c3VmbWR5YnR4aXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTc3NjcsImV4cCI6MjA1OTMzMzc2N30.0Nj6XUadler7H-zzQ_Z4yc_p-b5hLNLX1OLGnt8mBrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});